server:
  port: 3000

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/sporterbook
    username: postgres
    password: 123456
  mail:
    host: smtp.yandex.ru
    username: uw@dru.su
    password: 12345678
    port: 465
    protocol: smtps

jwt:
  token:
    secret: TestSecret
    expired: 360000000000 #for production use 10-15 min

common:
  cors-ip: http://localhost:8080
  path: uploads
  news-file-dir: uploads/img/news

